#!/usr/bin/env bash
set -e

#
# INITIALIZE
#

__PROGRAM__=$(basename $0)
__EXTENSION_NAME__=${__PROGRAM__##*-}
__GH_EXTENSION_DIR__="$(dirname "$0")"

#__VERBOSE__=

#
# IMPORTS
#

source "$__GH_EXTENSION_DIR__/source/extras/addons.sh"
source "$__GH_EXTENSION_DIR__/source/commands/add.help"

#
# VARS
#

#
# HELPERS
#

help() {
  echo -e "Manage repository topics

${BOLD}USAGE${RESET}
  gh ${__EXTENSION_NAME__} <command> [flags]

${BOLD}COMMANDS${RESET}
    add:  $(add:usage)

"
}

#
# LOGIC
#

if test $# -eq 0; then
  help
fi

while test $# -gt 0; do
  case "$1" in

  add)
    shift
    ${__GH_EXTENSION_DIR__}/source/commands/add.sh $*
    exit $?
    ;;

  rm)
    shift
    ${__GH_EXTENSION_DIR__}/source/commands/rm.sh $*
    exit $?
    ;;
  *)
    x:err "command[$1] not supported."
    help
    ;;

  esac
done
